import HomeBg from "../assets/dr.jpg"
import ambulancelights from "../assets/ambulance-lights.png"
import dr2 from "../assets/10.png"
import Diagnosis from "../assets/8.png"
import Pharmacist from "../assets/9.png"
import Firstscreen from "../assets/welcome.gif"
import MapUserPoint from "../assets/userPoint.png"
import MapClinicPoint from "../assets/afia.png"
import MapReset from "../assets/greenIndicator.png"
import Mastercard1 from "../assets/Mastercard.png"
import Visa1 from "../assets/Visa.png"
import med1 from "../assets/m1.png"
import med2 from "../assets/t1.png"
import ambulance from "../assets/ambulance.png"
import Avatar1 from "../assets/avatar.gif"
import Stripe1 from "./structure/stripe.png"
import Deli1 from "./structure/deli.png"


export const image_dr2= dr2;
export const image_HomeBg= HomeBg;
export const image_MapReset= MapReset;
export const image_MapClinicPoint= MapClinicPoint;
export const image_MapUserPoint= MapUserPoint;
export const image_Firstscreen= Firstscreen;
export const image_Pharmacist= Pharmacist;
export const image_Diagnosis= Diagnosis;
export const image_ambulancelights= ambulancelights;
export const Mastercard= Mastercard1;
export const Visa= Visa1;
export const Avatar= Avatar1;
export const Ambulance= ambulance;
export const M1= med1;
export const M2= med2;
export const Stripe= Stripe1
export const Deli= Deli1